import { Observable } from 'rxjs';
import { Hero, CreateHeroDto, UpdateHeroDto } from '../models/hero.model';

/**
 * HeroRepository contract (Domain layer)
 * 
 * Defines WHAT operations the system can perform with heroes.
 * Does NOT define HOW they are implemented.
 * 
 * Following Dependency Inversion Principle:
 * - High-level modules (use cases) depend on this abstraction
 * - Low-level modules (services) implement this abstraction
 */
export abstract class HeroRepository {
  /**
   * Get all heroes
   */
  abstract getAll(): Observable<Hero[]>;

  /**
   * Get a single hero by ID
   * @returns Hero if found, undefined otherwise
   */
  abstract getById(id: string): Observable<Hero | undefined>;

  /**
   * Search heroes by name (case-insensitive partial match)
   * @param term - Search term (e.g., "man" finds "Superman", "Spiderman")
   */
  abstract searchByName(term: string): Observable<Hero[]>;

  /**
   * Create a new hero
   * @param dto - Hero data (id and createdAt generated by system)
   */
  abstract create(dto: CreateHeroDto): Observable<Hero>;

  /**
   * Update an existing hero
   * @param id - Hero ID
   * @param dto - Fields to update (partial)
   */
  abstract update(id: string, dto: UpdateHeroDto): Observable<Hero>;

  /**
   * Delete a hero
   * @param id - Hero ID
   */
  abstract delete(id: string): Observable<void>;
}